### ISSUE TITLE
model部分各部分子模型的含义？

### ISSUE THREAD

**Issue by Senwang98** [Akeepers/LEAR#10]
@Akeepers 
hi，我这边在尝试使用你的代码，我发现模型这部分我不是太get到啥意思？
<img width="870" alt="image" src="https://user-images.githubusercontent.com/23122139/182789752-20adcfb3-6918-4cf3-916e-3096da8c812a.png">
上图中的四个模型分别是指？期待回复

**Comment by Senwang98** [comment]
不知道第一个是指MRC-NER的做法，第二个SERS是LEAR的做法？

**Comment by Akeepers** [comment]
是的，SERS是最初打算起的名字

**Comment by Senwang98** [comment]
@Akeepers 
ok，了解啦，谢谢

**Comment by Senwang98** [comment]
@Akeepers 
Hi，抱歉打扰，想再请教一下LEAR的工作。
1. 我查看了一下eval部分的代码，我发现这边的Fscore与序列标注那种BIO的预测不太一样，请问这是不是两种fscore？因为序列标注是直接token算fcore的，LEAR则是以span的gt作为分母的，这在paper中比较（Bert-Taager vs. LEAR）是合理的吗？或者说我根据LEAR的预测span手动给token打BIEO标签与当前代码中的比较的话，真的能保证一样的fcsore值吗？
2. 另外，当前code中有支持直接训练序列标注的方式吗？

期待回复

**Comment by Akeepers** [comment]
1. 一般来说，序列标注的BIO也是需要完整的预测出实体的位置 & 标签，这里和span算start/end/标签没有什么冲突吧
2. 印象中没有

**Comment by Senwang98** [comment]
@Akeepers 
Ok，所以我这边直接使用你的eval脚本应该可以跟seq-labeling公平比较吧？那我就没啥问题了
