### ISSUE TITLE
论文实验数据的问题

### ISSUE THREAD

**Issue by suolyer** [Akeepers/LEAR#11]
Hi～，最近做看 BERT-MRC 和 你的 LAER，有点好奇：
1）论文上的效果是取最高的分数吗，还是做几次实验，然后取平均值。
2）seed 设置为 42 效果会好很多吗，对比其他 seed 来说

**Comment by MoDawn** [comment]
请问需要的参数怎么设置的？没有找到，，提示说“error: the following arguments are required: --task_type, --task_save_name, --data_dir, --data_name, --model_name, --model_name_or_path, --output_dir”
