### ISSUE TITLE
--task_layer_lr这个参数的问题

### ISSUE THREAD

**Issue by starxiaoliu** [Akeepers/LEAR#14]
作者你好，
我想问一下下面这个参数的问题！
![屏幕截图 2023-04-14 091027](https://user-images.githubusercontent.com/119290651/231915850-b17fcd4f-e9f8-497e-879f-005bfe1fcc4b.png)
这个里边的参数和--task_layer_lr这个参数是一个么，为什么我在命令行输入的--task_layer_lr参数，在上边图片标注的跟我输入的不一样。

**Comment by Akeepers** [comment]
这是一个float值，从你的截图来看是精度的问题，一般没什么影响。

如果在意的话，可以保留xx位小数这样修改

**Comment by starxiaoliu** [comment]
这个不是那个任务层的学习率么，我是根据您论文里那个参数设置的--task_layer_lr=6e-5，然后上边那个图片里 跟我传入的参数不一样

**Comment by starxiaoliu** [comment]
![屏幕截图 2023-04-14 102047](https://user-images.githubusercontent.com/119290651/231925378-20755f6a-b39a-48f3-b854-748e1037e8ef.png)
![屏幕截图 2023-04-14 102014](https://user-images.githubusercontent.com/119290651/231925408-1d154210-f415-453c-8165-5d05954d18a1.png)
第一个图片是我设置传入的参数，然而下边那个跟我设置传入的不一样，这是没传入成功么

**Comment by Akeepers** [comment]
你检查下代码吧，看上去是的

**Comment by starxiaoliu** [comment]
好的，谢谢您了
