### ISSUE TITLE
The meaning of prefix 'first'

### ISSUE THREAD

**Issue by jinniulema** [Akeepers/LEAR#15]
Hello,  I find there are many variables which have a prefix 'first'. For example, 'first_label'. Can you explain the meaning of 'first' here?

**Comment by Akeepers** [comment]
* 'first' - trigger
* 'second' - argument

The 'first' is a code snippet related to the event extraction task. Please ignore if it's not relevant to your question.

**Comment by jinniulema** [comment]
Ok, thanks
