### ISSUE TITLE
模型涉及到label的参数设置

### ISSUE THREAD

**Issue by qry0120** [Akeepers/LEAR#18]
您好！
在看了您的论文之后，想试着在自己的数据集上看看效果，参数设置涉及到label的那块有些模糊不清，不知道您方便回答一下吗？
如果可以的话，给个具体的实例最好，麻烦啦！
就是以zh_msra为例，能否给一个使用您提出的模型时，配置参数该如何设置呢

**Comment by Akeepers** [comment]
没太get到，你说的参数是指模型超参吗

**Comment by qry0120** [comment]
您好，打扰了
这是在我这边的数据集上跑的模型超参数：
python run_ner.py --task_type "ner" --task_save_name "ner_xmt" --data_dir "E:/pycmprojects/obj_lear/data/ner/xmt" --data_name "xmt" --result_dir "E:/pycmprojects/obj_lear/LEAR_xmt_outputs/result" --model_name "SERS" --first_label_file "E:/pycmprojects/obj_lear/data/ner/xmt/processed/label_map.json" --label_str_file "E:/pycmprojects/obj_lear/data/ner/xmt/processed/label_annotation.txt" --model_name_or_path "E:/pycmprojects/pretrain_model/bert-base-chinese" --output_dir "E:/pycmprojects/obj_lear/LEAR_xmt_outputs"

现在问题就是
损失一直在9.7上保持不变
我debug调试完之后发现问题在 
    if args.model_name == 'SERS':
        # label_token_ids, label_input_mask, label_token_type_ids = get_label_data(
        #     args, tokenizer)

        # batch_label_token_ids = torch.tensor(
        #     label_token_ids, dtype=torch.long).to(args.device)
        # batch_label_input_mask = torch.tensor(
        #     label_input_mask, dtype=torch.float32).to(args.device)
        # batch_label_token_type_ids = torch.tensor(
        #     label_token_type_ids, dtype=torch.long).to(args.device)
        # print(batch_label_token_ids.shape)
        batch_label_token_ids, batch_label_token_type_ids, batch_label_input_mask = processor.get_label_data(
            args.device)
        global random_label_emb
        if args.use_random_label_emb and random_label_emb is None:
            random_label_emb = torch.rand(size=batch_label_token_ids.shape + (1024,))
这个部分输出了lable描述相关的信息，但是在
for cur_step, data in enumerate(train_bar):
关于标签描述的信息变成了全为0的张量，bert进行编码句子的文本信息时，输出的向量也全为0，所以损失才会不变不知道您是否可以帮忙解答一下

**Comment by qry0120** [comment]
就是加载一个batch的数据后，关于label 的token_ids,token_type_ids,变为了全为0的张量，bert进行编码时，输出也全为0的张量了，于是我将这句代码放到了for cur_step, data in enumerate(train_bar)这个循环里面
batch_label_token_ids, batch_label_token_type_ids, batch_label_input_mask = processor.get_label_data(
                        args.device,rebuild=True)
参数设置了rebuild=True，同样的在evaluate部分做相应改变，发现
results = self.bert(input_ids=data['token_ids'], token_type_ids=data['token_type_ids'],
                            attention_mask=data['input_mask'], output_attentions=return_bert_attention)
输出也为全0张量
实在不好意思，冒昧的给您发了这么多条信息，希望您可以在闲暇之余解答一下我的迷惑，万分感谢！

**Comment by qry0120** [comment]
哦，对了我在加载bert预训练模型时，将 gradient_checkpointing=args.gradient_checkpointing这个进行了删除，不知道何这个有没有关系

**Comment by qry0120** [comment]
如果不删除的话，会报这个错误
   model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'gradient_checkpointing'

**Comment by qry0120** [comment]
您好，就是不太懂编码标签描述信息的那块用处，我把自己的数据集中实体标签与之对应的描述换成了不相关的一些解释，但是发现模型的性能相差不太大，能不能麻烦您帮忙解答一下？
{
    "PER": "中国",
    "LOC": "美国",
    "ORG": "韩国",
    "POS": "菲律宾",
    "CON": "香港",
    "TIME": "澳门",
    "WORK":"日本"
}
