### ISSUE TITLE
你好，请问ED任务部分数据是什么样的呀

### ISSUE THREAD

**Issue by Tatrina** [Akeepers/LEAR#3]
就是processed下面，我看ner的已经有了，方便上传一下吗，或者给个sample？麻烦你了

**Comment by igorhuangchao** [comment]
you could refer to this project: [https://github.com/thunlp/HMEAE](url), which find from the last page of the paper.
by the way, the ACE 2005 is not free.  good luck.

**Comment by Tatrina** [comment]
> you could refer to this project: [https://github.com/thunlp/HMEAE](url), which find from the last page of the paper. by the way, the ACE 2005 is not free. good luck.
thanks, I didn't notice the information in the readme before.

**Comment by Akeepers** [comment]
Thinks @igorhuangchao, his reply is on the point. Besides, `thunlp` has updated the repo [HMEAE](https://github.com/thunlp/HMEAE).  You should use the earlier version.
