### ISSUE TITLE
Visualization of the Proposed Model?

### ISSUE THREAD

**Issue by yc1999** [Akeepers/LEAR#7]
Hi~in your paper, you show us a picture which indicates the non-effective attention mechanism of previous models:

![image](https://user-images.githubusercontent.com/37548571/148713645-d7d9b37c-17be-4bb0-92e6-4e0ffb074479.png)

I am wondering whether you can show us a picture  like the above picture to demonstrate the effectiveness of LEAR's attention mechanism? Thank you~

**Comment by Akeepers** [comment]
Sorry, no such experiment has been done before.
